# Generated by Django 4.0.1 on 2022-02-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viruss', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesUpload',
        ),
    ]
