# Generated by Django 4.0.1 on 2022-02-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viruss', '0002_delete_filesupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pictures')),
                ('Test_Date', models.CharField(max_length=20)),
                ('Test_Type', models.CharField(max_length=20)),
                ('Test_ID', models.IntegerField()),
                ('PCR_Pos_Neg', models.CharField(max_length=1)),
                ('Subject_Age', models.CharField(max_length=2)),
                ('Symptomatique_Asymptomatique', models.CharField(max_length=20)),
            ],
        ),
    ]
