# Generated by Django 4.0.1 on 2022-02-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viruss', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesUpload',
        ),
    ]
